spring:
  application:
    name: feign-application
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        password: nacos
        username: nacos
server:
  port: 9099
feign:
  httpclient:
    enabled: true