#spring:
#  application:
#    name: dtp-services
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml

server:
  port: 8090

#dtp:
#  threadPool:
#    coreSize: 5
#    maxSize: 10
